from PySide6.QtWidgets import QComboBox,QDoubleSpinBox,QFormLayout,QLabel,QVBoxLayout,QWizardPage
from ...constants import OUTER_EDGE_HELP
from ...enums import EdgeReferenceType,OuterBoundaryType,SurfaceType
from ...models import SideBoundaryInput
from ..widgets import HelpPanel
class BoundaryPage(QWizardPage):
    def __init__(self,side):
        super().__init__(); self.side=side; self.setTitle(f"{side.title()} outer boundary"); self.edge=QComboBox(); self.edge.addItem("Select…",None); self.edge.addItem("Physically marked outer traffic-edge line",EdgeReferenceType.MARKED_OUTER_TRAFFIC_EDGE_LINE); self.edge.addItem("Designed outer traffic-edge line",EdgeReferenceType.DESIGNED_OUTER_TRAFFIC_EDGE_LINE); self.edge.addItem("Kerb is the outer travelled edge",EdgeReferenceType.KERB_IS_OUTER_TRAVELLED_EDGE); self.outer=QComboBox(); self.outer.addItem("Kerb",OuterBoundaryType.KERB); self.outer.addItem("Edge of seal",OuterBoundaryType.EDGE_OF_SEAL); self.outer.addItem("Authority-defined side boundary",OuterBoundaryType.AUTHORITY_DEFINED); self.surface=QComboBox(); self.surface.addItem("Sealed",SurfaceType.SEALED); self.surface.addItem("Unsealed",SurfaceType.UNSEALED); self.distance=QDoubleSpinBox(); self.distance.setRange(0,100); self.distance.setDecimals(2); self.distance.setSpecialValueText("Confirm zero / enter distance"); self.distance.setSuffix(" m"); self.allowance=QDoubleSpinBox(); self.allowance.setRange(0,100); self.allowance.setDecimals(2); self.allowance.setSpecialValueText("Required"); self.allowance.setSuffix(" m"); layout=QVBoxLayout(self); form=QFormLayout(); form.addRow("What defines the outer travelled edge?",self.edge); form.addRow("What is beyond it?",self.outer); form.addRow("Surface beyond outer edge",self.surface); form.addRow("Distance to kerb or edge of seal",self.distance); form.addRow("Authority side allowance",self.allowance); layout.addLayout(form); self.sketch=QLabel("Road  · · ·  OUTER TRAFFIC-EDGE LINE  ─── sealed/unsealed area ───  kerb / edge of seal"); self.sketch.setStyleSheet("padding:10px;background:#eef3f7"); layout.addWidget(self.sketch); layout.addWidget(HelpPanel(OUTER_EDGE_HELP+" Centre lines, turn-lane lines and painted-island lines cannot be selected here. Unsealed width is recorded but excluded.")); self.edge.currentIndexChanged.connect(self._mode); self.outer.currentIndexChanged.connect(self._mode); self.surface.currentIndexChanged.connect(self.completeChanged); self.distance.valueChanged.connect(self.completeChanged); self.allowance.valueChanged.connect(self.completeChanged); self._mode()
    def _mode(self):
        at_kerb=self.edge.currentData()==EdgeReferenceType.KERB_IS_OUTER_TRAVELLED_EDGE
        if at_kerb:self.outer.setCurrentIndex(self.outer.findData(OuterBoundaryType.KERB)); self.surface.setCurrentIndex(self.surface.findData(SurfaceType.SEALED)); self.distance.setValue(0)
        self.outer.setEnabled(not at_kerb); self.surface.setEnabled(not at_kerb); self.distance.setEnabled(not at_kerb); self.allowance.setVisible(self.outer.currentData()==OuterBoundaryType.AUTHORITY_DEFINED); self.completeChanged.emit()
    def isComplete(self):
        if self.wizard() and getattr(self.wizard(),"cross_section_page",None) and self.wizard().cross_section_page.full.isChecked():return True
        return self.edge.currentData() is not None and (self.outer.currentData()!=OuterBoundaryType.AUTHORITY_DEFINED or self.allowance.value()>0)
    def boundary(self):return SideBoundaryInput(edge_reference=self.edge.currentData(),outer_boundary=self.outer.currentData(),surface_beyond_edge=self.surface.currentData(),distance_from_outer_edge_m=self.distance.value(),authority_allowance_m=self.allowance.value() if self.outer.currentData()==OuterBoundaryType.AUTHORITY_DEFINED else None)
    def copy_from(self,other):self.edge.setCurrentIndex(self.edge.findData(other.edge.currentData())); self.outer.setCurrentIndex(self.outer.findData(other.outer.currentData())); self.surface.setCurrentIndex(self.surface.findData(other.surface.currentData())); self.distance.setValue(other.distance.value()); self.allowance.setValue(other.allowance.value())
    def load_boundary(self,side):
        self.edge.setCurrentIndex(self.edge.findData(side.edge_reference)); self.outer.setCurrentIndex(self.outer.findData(side.outer_boundary)); self.surface.setCurrentIndex(self.surface.findData(side.surface_beyond_edge)); self.distance.setValue(side.distance_from_outer_edge_m); self.allowance.setValue(side.authority_allowance_m or 0)
class LeftBoundaryPage(BoundaryPage):
    def __init__(self):super().__init__("left")
